[book]
authors = ["Lefteris Lazaropoulos, Zoe Paraskevopoulou, Anja Petkovic Komel, Sophie Rain, dxo"]
language = "en"
src = "src"
title = "The act Book"

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[preprocessor.katex]
after = ["links"]

[output]

[output.html]
additional-css = ["theme/custom.css"]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
site-url = "/act/"
git-repository-url = "https://github.com/argotorg/act"

[output.html.playground]
editable = true
copy-js = true
line-numbers = true
