{-
 -
 - rocq backend for act
 -
 - unsupported features:
 - + bytestrings
 - + external storage
 - + casting from addresses to contract
 -
 - TODO: Replace THIS with NextAddr in constrs
 - -}

{-# Language OverloadedStrings #-}
{-# Language RecordWildCards #-}
{-# LANGUAGE GADTs #-}
{-# Language DataKinds #-}
{-# Language ViewPatterns #-}
{-# Language TupleSections #-}


module Act.Rocq (rocq) where

import Prelude hiding (GT, LT)

import Data.Map.Strict (Map)
import Data.Tuple.Extra
import qualified Data.Map.Strict    as M
import qualified Data.List.NonEmpty as NE
import qualified Data.Text          as T
import Data.List (inits, intercalate)
import Data.List.Extra (snoc, unsnoc)
import Control.Monad.State
import Data.Maybe (mapMaybe, maybeToList, fromMaybe)

import EVM.ABI
import Act.Syntax
import Act.Syntax.TypedExplicit
import Debug.Trace

type Fresh = State Int

header :: T.Text
header = T.unlines
  [ "(* --- GENERATED BY ACT --- *)\n"
  , "Require Import Stdlib.ZArith.ZArith."
  , "Require Import ActLib.ActLib."
  , "Require Stdlib.Strings.String.\n"
  , "Module " <> strMod <> " := Stdlib.Strings.String."
  , "Open Scope Z_scope.\n"
  ]

-- | produce a coq representation of a specification
rocq :: Act -> T.Text
rocq (Act store contracts) =
  header <> (T.intercalate "\n\n" $ contractCode store <$> contracts)

contractCode :: StorageTyping -> Contract -> T.Text
contractCode store (Contract _ ctor@Constructor{..} behvs) = T.unlines $
  [ "Module " <> T.pack _cname <> ".\n" ]
  <> [ stateRecord ]
  <> [ zeroState store ctor ]
  <> [ sendValueState store ctor ]
  <> [ contractAddressIn _cname store ]
  -- <> [ addressIn _cname store ]
  <> [ noAliasing _cname store ]
  -- <> [ intBounds _cname store ]
  <> [ intBoundsRec _cname store ]
  <> [ nextAddrConstraint ]
  <> [ constructorCode store ctor ] <> ( transitionCode store <$> behvs ) -- <> ( behaviourCode store <$> behvs )
  -- <> [ localStep _cname behvs]
  -- <> [ extStep _cname store ]
  <> [ printInductive $ step _cname store ctor behvs ]
  -- <> [ multistep ]
  <> [ reachable ]
  -- <> [ reachableFromInit ctor]
  <> [ stepBefore ]
  -- <> [ multistepBefore ]
  -- <> [ reachableBefore ]
  -- -- <> ( postCondConstr ctor )
  -- -- <> ( concatMap postCondBehv behvs )
  -- <> [ invariantInit ctor ]
  -- <> [ invariantStep ctor ]
  -- <> [ invariantReachable ctor]
  <> [ "End " <> T.pack _cname <> "." ]
  where

    stateRecord = T.unlines

      [ "Record" <+> stateType <+> ": Set :=" <+> stateConstructor
      , "{ " <> T.intercalate ("\n" <> "; ") (addrFieldDecl : map decl (M.toList store'))
      , "}."
      ]

    decl (n, (s, _)) = (T.pack n) <> " : " <> valueType s

    store' = contractStore _cname store

zeroState :: StorageTyping -> Constructor -> T.Text
zeroState store (Constructor _ name _ _ _ _ _) = definition zeroStateType (declTerm nextAddrVar) $ stateval True store name 0 (\_ t -> defaultVal t) []

zeroStateType :: T.Text
zeroStateType = "zeroState"

zeroStateVar :: Term
zeroStateVar = Term zeroStateType stateType

sendValueState :: StorageTyping -> Constructor -> T.Text
sendValueState store (Constructor _ name _ _ _ _ _) =
  definition sendValueStateType (declTerms [stateVar, valVar]) $ stateval False store name 0
    (\r _ -> case r of
      SVar _ _ _ _ "BALANCE" -> parens $ "BALANCE" <+> term stateVar <+> "-" <+> term valVar 
      _ -> ref r
      ) []

  where valVar = Term "v" "Z"

sendValueStateType :: T.Text
sendValueStateType = "sendValue"

sendValueStateVar :: Term
sendValueStateVar = Term sendValueStateType "WHAT??TODO"

constructorCode :: StorageTyping -> Constructor -> T.Text
constructorCode store (Constructor _ cname iface _ block _ _) = T.unlines $
  (traverseBlock cname store [] [] [] f block)
  <> [construction' cname iface store block]
  <> [ initState iface ]
  -- <> [ initStateBefore iface ]
  -- <> [ invariants iface invs ]
  where
    f caseids inters _ iffs upds _ =
      [ preBlock True cname iface inters caseids iffs
      , updBlock True cname cname iface store inters caseids upds
      ]

transitionCode :: StorageTyping -> Behaviour -> T.Text
transitionCode store (Behaviour _ name cname iface _ block _) = T.unlines $
  (traverseBlock name store [] [] [] f block)
  -- <> [transition' name iface store block]
  -- <> [ initState iface ]
  -- <> [ initStateBefore iface ]
  -- <> [ invariants iface invs ]
  where
    f caseids inters _ iffs upds _ =
      [ preBlock False name iface inters caseids iffs
      , updBlock False name cname iface store inters caseids upds
      ]


type CaseId = Int

traverseBlock :: Id -> StorageTyping -> [CaseId] -> [Interaction] -> [Exp ABoolean] ->
                  ([CaseId] -> [Interaction] -> [Exp ABoolean] -> [Exp ABoolean] -> [StorageUpdate] -> Bool -> [a]) -> Block -> [a]
traverseBlock name store caseids inters cconds f (Block iff cases) = concatMap (uncurry $ traverseCase f) $ zip [0..] cases
  where
    traverseCase :: ([CaseId] -> [Interaction] -> [Exp ABoolean] -> [Exp ABoolean] -> [StorageUpdate] -> Bool -> [a]) -> CaseId -> Case -> [a]
    traverseCase f' caseid (Case _ cond (LocalOnly upds _ )) = f' (snoc caseids caseid) inters (snoc cconds cond) iff upds True
    traverseCase f' caseid (Case _ cond (LocalAndInteraction upds inter block )) =
      (f' (snoc caseids caseid) inters (snoc cconds cond) iff upds False)
      ++ traverseBlock name store (snoc caseids caseid) (snoc inters inter) (snoc cconds cond) f' block



argsFromIface :: Interface -> [Arg]
argsFromIface (Interface _ args) = args

argsFromInteraction :: Interaction -> [Arg]
argsFromInteraction (TypedCallI _ _ _ _ _ _ success iface) = (Arg (AbiArg AbiBoolType) success) : maybe [] argsFromIface iface
argsFromInteraction (UntypedCallI _ _ _ _ _ _ success iface) = (Arg (AbiArg AbiBoolType) success) : maybe [] argsFromIface iface
argsFromInteraction (CreateI _ ret _ _ _) =  [Arg (AbiArg AbiAddressType) ret]

successFromInteraction :: Interaction -> Id
successFromInteraction (TypedCallI _ _ _ _ _ _ success _) = success
successFromInteraction (UntypedCallI _ _ _ _ _ _ success _) = success

valFromInteraction :: Interaction -> Exp AInteger
valFromInteraction (TypedCallI _ _ _ _ _ val _ _) = fromMaybe (LitInt nowhere 0) val
valFromInteraction (UntypedCallI _ _ _ _ _ val _ _) = fromMaybe (LitInt nowhere 0) val

argTermsFromInters :: Interaction -> [Term]
argTermsFromInters = argTerms . argsFromInteraction

caseIdxSuf :: [Int] -> T.Text
caseIdxSuf idcs = "c_" <> (T.intercalate "_" $ T.pack . show <$> idcs)


-- TODO: Lefteris: FIX NextAddr HANDLING
-- | definition of precondition block
preBlock :: Bool -> Id -> Interface -> [Interaction] -> [CaseId] -> [Exp ABoolean] -> T.Text
preBlock isCtor name iface inters idcs conds = printInductive $
  Inductive rtype [] args "Prop"
    [IConstr
      (rtype <> "C") args
      ((nameHypothesis "iff" $ coqprop <$> conds)
      ++ [(Term "stateBounds" (integerBoundsType <+> term stateVar)) | not isCtor]
      ++ concat [maybeToList $ Term "CallerBound" <$> coqbound ("Caller" <+> term envVar) (ValueType TAddress)]
      )
      [rtype <+> terms args]
    ]
  []
  where
    rtype = T.pack name <> "_iff_" <> caseIdxSuf idcs
    numInters = length inters
    args = ([envVar] ++ ifaceTerms iface ++ concatMap argTermsFromInters inters ++ [stateVar | not isCtor] ++ [nextAddrVar] ++ iStateVars numInters)

-- | definition of update block
updBlock :: Bool -> Id -> Id -> Interface -> StorageTyping -> [Interaction] -> [CaseId] -> [StorageUpdate] -> T.Text
updBlock isCtor name cname iface store inters idcs updates = printInductive $
  Inductive rtype [] (args ++ [stateVar']) "Prop"
    [IConstr
      (rtype <> "C") (args ++ [stateVar'])
      []
      [rtype <+> terms args
        <+> parens (stateval isCtor store cname numInters (\r _ -> ref r) updates)]
    ]
  []
  where
    rtype = T.pack name <> "_upd_" <> caseIdxSuf idcs
    numInters = length inters
    args = ([envVar] ++ ifaceTerms iface ++ concatMap argTermsFromInters inters ++ [stateVar, nextAddrVar] ++ iStateVars numInters) -- ++ [stateVar'])

construction' :: Id -> Interface -> StorageTyping -> Block -> T.Text
construction' name iface store block = printInductive $
  Inductive constructorType [] args "Prop"
  (traverseBlock name store [] [] [] f block)
  []
  where
    f caseids inters conds _ _ isEndpoint = caseCtor caseids inters conds isEndpoint

    args = ([envVar] ++ ifaceTerms iface ++ [nextAddrVar, stateVar', nextAddrVar'])

    caseCtor :: [CaseId] -> [Interaction] -> [Exp ABoolean] -> Bool -> [InductiveConstr]
    caseCtor _ _ _ False = []
    caseCtor caseids inters conds True = do
      let name' = T.pack name <> caseIdxSuf caseids
      let body = ((concatMap (uncurry3 segment) $ zip3 (drop 1 $ inits caseids) (inits inters) conds)
                  <> [constructorType <+> terms args])
      pure (IConstr name' caseargs [] body)
      where
        numInters = length inters
        interTerms = concatMap argTermsFromInters inters
        caseargs =  ([envVar] ++ ifaceTerms iface ++ interTerms ++ [nextAddrVar, stateVar', nextAddrVar'] ++ iStateVars' (numInters - 0))

        segment :: [CaseId] -> [Interaction] -> Exp ABoolean -> [T.Text]
        segment caseids' inters' cond =
          [ T.pack name <> "_iff_" <> caseIdxSuf caseids' <+> terms ([envVar] ++ ifaceTerms iface ++ interTerms' ++ [nextAddrVar] ++ iStateVars (numInters' - 0))
          , coqprop cond
          , T.pack name <> "_upd_" <> caseIdxSuf caseids' <+> terms ([envVar] ++ ifaceTerms iface ++ interTerms') <+> parens (terms [zeroStateVar, nextAddrVar]) <+> terms ([nextAddrVar] ++ iStateVars (numInters' - 0)) <+> term finalState
          ]
          where finalState | length caseids' == length caseids = stateVar'
                           | otherwise = iStateVar' (length caseids' - 1)
                interTerms' = concatMap argTermsFromInters inters'
                segargs = [envVar] ++ ifaceTerms iface ++ interTerms' ++ [nextAddrVar] ++ iStateVars' (numInters' - 0) -- ++ [stateVar', nextAddrVar'])
                -- segterms = terms segargs1 <+> parens (terms [zeroStateVar, nextAddrVar]) <+> terms segargs2
                numInters' = length inters'

transition' :: StorageTyping -> Behaviour -> Inductive -- Id -> Interface -> StorageTyping -> Block -> Inductive
transition' store (Behaviour _ name _ iface _ block _) = 
  Inductive (T.pack name <> "_transition") [] args "Prop"
  (traverseBlock name store [] [] [] f block)
  []
  where
    f caseids inters conds _ _ isEndpoint = caseCtor caseids inters conds isEndpoint

    args = ([envVar] ++ ifaceTerms iface ++ [stateVar, nextAddrVar, stateVar', nextAddrVar'])

    caseCtor :: [CaseId] -> [Interaction] -> [Exp ABoolean] -> Bool -> [InductiveConstr]
    caseCtor _ _ _ False = []
    caseCtor caseids inters conds True = do
      let name' = T.pack name <> caseIdxSuf caseids
      let body = (concatMap (uncurry3 segment) $ zip3 (drop 1 $ inits caseids) (inits inters) conds)
            <> [T.pack name <> "_transition" <+> terms args]
      pure (IConstr name' caseargs [] body)
      where
        numInters = length inters
        caseargs =  ([envVar] ++ ifaceTerms iface ++ concatMap argTermsFromInters inters ++ iStateVars' (numInters - 0) ++ [stateVar,nextAddrVar,stateVar',nextAddrVar'])

        segment :: [CaseId] -> [Interaction] -> Exp ABoolean -> [T.Text]
        segment caseids' inters' cond =
          (if not isStartpoint then [unknownCallType <+> parens (coqexp $ valFromInteraction (last inters')) <+> terms [iStateVar' (length caseids'-2), iStateVar (length caseids'-1)] <+> (T.pack $ successFromInteraction (last inters'))] else [])
          <>
          [ T.pack name <> "_iff_" <> caseIdxSuf caseids' <+> terms segargs
          , coqprop cond
          , T.pack name <> "_upd_" <> caseIdxSuf caseids' <+> terms (segargs ++ [finalState])
          ]
          where isEndpoint = length caseids' == length caseids
                isStartpoint = length caseids' <= 1
                finalState | isEndpoint = stateVar'
                           | otherwise = iStateVar' (length caseids' - 1)
                segargs = ([envVar] ++ ifaceTerms iface ++ concatMap argTermsFromInters inters' ++ [stateVar, nextAddrVar] ++ iStateVars (numInters' - 0))
                numInters' = length inters'

        multis :: [Interaction] -> [T.Text]
        multis inters' = (\(t1,t2) -> multistepType <+> terms [t1,t2]) <$> iStateVarPairs' (length inters')



-- | definition of constructor preconditions
initPrecs :: Interface -> [Exp ABoolean] -> T.Text
initPrecs i conds = printInductive $ Inductive
  initPrecsType
  []
  ([envVar] ++ ifaceTerms i ++ [nextAddrVar])
  "Prop"
  [IConstr (initPrecsType <> "C")
           []
           (concat
           [ nameHypothesis "iff" $ coqprop <$> conds
           , map (uncurry Term) $ interfaceConstraints i
           , maybeToList (fmap (\h -> Term "CallerBound" h) $ coqbound ("Caller" <+> term envVar) (ValueType TAddress))
           , maybeToList (fmap (\h -> Term "OriginBound" h) $ coqbound ("Origin" <+> term envVar) (ValueType TAddress))
           , maybeToList (fmap (\h -> Term "ThisBound" h) $ coqbound ("This" <+> term envVar) (ValueType TAddress))
           , maybeToList (fmap (\h -> Term "NextAddressBound" h) $ coqbound "NextAddr" (ValueType TAddress))
           , [Term "Caller_lt_NextAddr" $ "Caller" <+> term envVar <+> "<" <+> term nextAddrVar]
           , [Term "Origin_lt_NextAddr" $ "Origin" <+> term envVar <+> "<" <+> term nextAddrVar]
           , [Term "This_eq_NextAddr" $ "This" <+> term envVar <+> "=" <+> term nextAddrVar]
           ])
           [initPrecsType <+> terms ([envVar] ++ ifaceTerms i ++ [nextAddrVar])]]
  []

nameHypothesis :: T.Text -> [T.Text] -> [Term]
nameHypothesis name hyps = uncurry go <$> zip [0..] hyps
  where
    go :: Int -> T.Text -> Term
    go i h = Term (name <> (T.pack $ show i)) h

indicesList :: [T.Text] -> T.Text
indicesList is = T.intercalate " -> " is

argList :: [T.Text] -> T.Text
argList = T.unwords

{-
-- | Relation characterizing constructor calls
construction' :: StorageTyping -> Id -> Interface -> [Case] -> T.Text
construction' store name i cases = inductive
  constructorType
  (argList $ [envDecl] <> interface' i <> [nextAddrDecl])
  (indicesList [stateType, addressType, "Prop"])
  (evalSeq caseCtor cases)
  where
    caseCtor :: Case -> Fresh (T.Text, T.Text, T.Text)
    caseCtor (Case _ caseCond updates) = do
      caseId <- getIncr
      let name' = T.pack name <> caseSuffix caseId
      -- let createsName = name' <> "_creates"
      let body = indent 2 ((namedHyps . concat $
            [ [("conds", initPrecsType <+> envVar <+> arguments i <+> nextAddrVar) ]
            , [("case_cond", coqprop caseCond) ]
            , nameHypothesis ("bindings") bindingsHyp
            ]) <> ",\n"
            <> (constructorType <+> envVar <+> arguments i <+> nextAddrVar <+> parens s <+> parens (iNextAddr finalI)))
      pure (name', "forall" <+> bindings', body)
      where 
        s = stateval True store name (\_ t -> defaultVal t) updates
        bindingsHyp = snd <$> bindings
        bindings' = case concatMap fst bindings of
          [] -> ""
          l -> argList l
-}

-- | predicate characterizing all initial (post constructor) states
initState :: Interface -> T.Text
initState i = printInductive $ Inductive
  initStateType
  []
  [stateVar]
  "Prop"
  [IConstr "fromConstructor"
           ([envVar] ++ ifaceTerms i ++ [stateVar, nextAddrVar, nextAddrVar'])
           []
           [ constructorType <+> terms ([envVar] ++ ifaceTerms i ++ [nextAddrVar, stateVar, nextAddrVar'])
           , initStateType <+> term stateVar
           ]]
  []


-- | predicate characterizing all initial (post constructor) states
initStateBefore :: Interface -> T.Text
initStateBefore i = printInductive $ Inductive
  initStateBeforeType
  []
  [boundVar, stateVar]
  "Prop"
  [IConstr "fromConstructorBefore"
           ([envVar] ++ ifaceTerms i ++ [nextAddrVar, nextAddrVar'])
           []
           [ constructorType <+> terms ([envVar] ++ ifaceTerms i ++ [nextAddrVar, stateVar, nextAddrVar'])
           , term nextAddrVar' <+> "<=" <+> term boundVar
           , initStateBeforeType <+> term boundVar <+> term stateVar
           ]]
  []

{-
-- | predicate characterizing all initial (post constructor) states that can be instantiated before a given environment
initStateBefore :: Id -> Interface -> Cases [StorageUpdate] -> T.Text
initStateBefore name i cases = inductive
  initStateBeforeType "" (boundType <+> "->" <+> stateType <+> "->" <+> "Prop") (evalSeq caseCtor cases)
  where
    baseval n = parens $ "snd" <+> parens (T.pack n <+> nextAddrVar <+> envVar <+> arguments i)
    finalAddr n = parens $ "fst" <+> parens (T.pack n <+> nextAddrVar <+> envVar <+> arguments i)

    caseCtor :: Case -> Fresh (T.Text, Maybe T.Text, T.Text)
    caseCtor (Case _ caseCond _) = do
      name' <- freshId name
      let createsName = name' <> "_creates"
      let body = (indent 2) . implication . concat $
            [ [initPrecsType <+> nextAddrVar <+> envVar <+> arguments i]
            , interfaceConstraints i
            , ["Caller" <+> envVar <+> "<" <+> nextAddrVar]
            , ["Origin" <+> envVar <+> "<" <+> nextAddrVar]
            , ["This" <+> envVar <+> "=" <+> nextAddrVar]
            , [ finalAddr createsName <+> "<=" <+> boundVar]
            , [ coqprop caseCond ]
            , [initStateBeforeType <+> boundVar <+> baseval createsName]
            ]
      pure (T.pack name' <> "_before", Just $ boundDecl <+> nextAddrDecl <+> envDecl <+> stateDecl <+> interface i, body)
  -}

{-
behaviourCode :: StorageTyping -> Behaviour -> T.Text
behaviourCode store (Behaviour _ name cname iface _ blocks _) = T.unlines $
  [ behvConds name iface precs ]
  <> [ behvPred store name cname iface cases ]
  <> [ retVal name iface cases ]

-- | definition of behaviour-case conditions
behvConds :: Id -> Interface -> [Exp ABoolean] -> T.Text
behvConds name i conds = do
  inductive
    (T.pack name <> "_conds") (envDecl <+> interface i <+> stateDecl <+> nextAddrDecl ) "Prop" [((T.pack name <> "_condsC"), "forall", body name)]
  where
    body n = indent 2 ((namedHyps . concat $
      [ nameHypothesis "iff" $ coqprop <$> conds
      , [("nextAddrCnstrnt_State", nextAddrConstraintType <+> nextAddrVar <+> stateVar) ]
      , interfaceConstraints i
      , maybeToList (("CallerBound",) <$> coqbound ("Caller" <+> envVar) (ValueType TAddress))
      , maybeToList (("OriginBound",) <$> coqbound ("Origin" <+> envVar) (ValueType TAddress))
      , maybeToList (("ThisBound",) <$> coqbound ("This" <+> envVar) (ValueType TAddress))
      , maybeToList (("NextAddressBound",) <$> coqbound ("NextAddr") (ValueType TAddress))
      , [("This_lt_NextAddr", "This" <+> envVar <+> "<" <+> nextAddrVar)]
      , [("Caller_lt_NextAddr", "Caller" <+> envVar <+> "<" <+> nextAddrVar)]
      , [("Origin_lt_NextAddr", "Origin" <+> envVar <+> "<" <+> nextAddrVar)]
      , [("no_self_call", parens $ "forall (p : address)," <+> addressInType <+> stateVar <+> "p" <+> "->" <+> "Caller" <+> envVar <+> "<>" <+> "p") ]
      , [("no_self_origin", parens $ "forall (p : address)," <+> addressInType <+> stateVar <+> "p" <+> "->" <+> "Origin" <+> envVar <+> "<>" <+> "p") ]
      , [("This_eq_addState", "This" <+> envVar <+> "=" <+> addrField <+> stateVar)]
      ]) <> ",\n"
      <> (T.pack n <> "_conds") <+> envVar <+> arguments i <+> stateVar <+>nextAddrVar )

behvUpdates :: StorageTyping -> Id -> Id -> Interface -> Case -> Fresh T.Text
behvUpdates store name cname iface (Case _ _ (updates, _)) = do
  name' <- freshId name
  let createsName = name' <> "_updates"
  pure $ transition store createsName cname iface updates


behvCall :: Id -> Interface -> [Case] -> T.Text
behvCall name iface cases = case unsnoc (zip ([0..] :: [Int]) cases) of
  Just (cases', (lastCaseNum, _)) ->
    definition (T.pack name <> "_call") (nextAddrDecl <+> envDecl <+> stateDecl <+> interface iface)
    (foldr iteCase (caseText lastCaseNum) cases')
  Nothing -> error "Internal error: empty constructor cases list"
  where
    caseText i = T.pack (name <> show i) <> "_updates" <+> nextAddrVar <+> envVar <+> stateVar <+> arguments iface

    iteCase :: (Int, Case) -> T.Text -> T.Text
    iteCase (i, (Case _ casecond _)) elseText =
      "if" <+> (coqbool casecond) <+>
      "then" <+> caseText i <+>
      "else" <+> elseText

behvPred :: StorageTyping -> Id -> Id -> Interface -> [Case] -> T.Text
behvPred store name cname i cases = inductive
  (T.pack name <> "_transition") (argList $ [envDecl] <> interface' i <> [stateDecl, nextAddrDecl])  (indicesList $ [stateType, addressType, "Prop"]) caseCtors
  where
    caseCtors = (evalSeq caseCtor cases)

    caseCtor :: Case -> Fresh (T.Text, T.Text, T.Text)
    caseCtor (Case _ caseCond (updates, _)) = do
      caseId <- getIncr
      -- name' <- fresh name
      pure (T.pack name <> caseSuffix caseId, "forall" <+> bindings', caseBody caseCond)
      where 
        (s, bindings, finalI) = stateval False store cname (\r _ -> ref r) updates
        bindingsHyp = snd <$> bindings
        bindings' = case concatMap fst bindings of
          [] -> ""
          l -> argList l

        caseBody c = indent 2 ((namedHyps . concat $
          [ [("conds", (T.pack name) <> "_conds" <+> envVar <+> arguments i <+> stateVar <+> nextAddrVar) ]
          , [("case_cond", coqprop c) ]
          , nameHypothesis ("bindings") bindingsHyp
          ]) <> ",\n"
          <> (T.pack name <> "_transition") 
            <+> envVar
            <+> arguments i
            <+> stateVar
            <+> nextAddrVar
            <+> parens s
            <+> parens (iNextAddr finalI)
            )
            -}


-- | Inductive definition of step relation of 2 states
-- that takes into account only transitions of the current contract type
localStep :: Id -> [Behaviour] -> Inductive
localStep contract behvs = Inductive
  (localStepType contract)
  []
  args
  "Prop"
  (stepBehv <$> behvs)
  []
  where
    -- | constructor for the step relation
    stepBehv :: Behaviour -> InductiveConstr
    stepBehv (Behaviour _ name _ i _ _ _) = IConstr
      (T.pack name <> "_" <> T.pack contract <> "_transition")
      ([envVar] ++ ifaceTerms i ++ [stateVar, nextAddrVar, stateVar', nextAddrVar'])
      []
      [ T.pack name <> "_transition" <+> terms ([envVar] ++ ifaceTerms i ++ [stateVar, nextAddrVar, stateVar', nextAddrVar'])
      , localStepType contract <+> terms args
      ]

    args = [envVar, stateVar, nextAddrVar, stateVar', nextAddrVar']

-- | Constraint on Env expressing that the NextAddr field should be greated than
-- all addresses contained in the state
nextAddrConstraint :: T.Text
nextAddrConstraint = definition
  nextAddrConstraintType (declTerm nextAddrVar <+> declTerm stateVar) body
    where
      body = indent 2 $ forAll (parens ("p : address")) <+>
        (addressInType <+> term stateVar <+> "p" ) <+> "->" <+> (term nextAddrVar <+> "> p")

-- | Inductive definition of step relation of 2 states
-- that takes into account transitions of the current contract type
-- and all transitions possible for contained contracts
extStep :: Id -> StorageTyping -> Inductive
extStep main store = Inductive
  extStepType
  []
  [envVar, stateVar, nextAddrVar, stateVar', nextAddrVar']
  "Prop"
  body
  []
    where
    body =
      IConstr (extStepType <> "_" <> T.pack main) [] mainargs
              [ localStepType main <+> terms mainargs
              , extStepType <+> terms mainargs
              ]
      : mapMaybe (uncurry substep) (M.toList localStore)

    mainargs = [envVar, stateVar, nextAddrVar, stateVar', nextAddrVar']

    localStore = contractStore main store

    substep :: Id -> (ValueType, Integer) -> Maybe InductiveConstr
    substep var (ValueType (TContract cid), _) = Just $ IConstr (extStepType <> "_" <> varp) [] mainargs items
      where
        varp = T.pack var
        items = concat
          [ [ nextAddrConstraintType <+> term nextAddrVar <+> term stateVar ]
          , [ parens $ "forall (p : address)," <+> addressInType <+> term stateVar <+> "p" <+> "->" <+> "Origin" <+> term envVar <+> "<>" <+> "p" ]
          , [ parens $ "forall (p : address)," <+> addressInType <+> term stateVar <+> "p" <+> "->" <+> "Caller" <+> term envVar <+> "<>" <+> "p" ]
          , [ integerBoundsType <+> term stateVar ]
          , [ T.pack cid <.> extStepType <+> term envVar <+> parens (varp <+> term stateVar) <+> term nextAddrVar <+> parens (varp <+> term stateVar') <+> term nextAddrVar' ]
          , [ addrField <+> term stateVar <+> "=" <+> addrField <+> term stateVar' ]
          , (\var' -> parens (T.pack var' <+> term stateVar) <+> "=" <+> parens (T.pack var' <+> term stateVar')) <$> (filter (var /=) $ M.keys localStore)
          , [ extStepType <+> terms [envVar, stateVar, nextAddrVar, stateVar', nextAddrVar'] ]
          ]
    substep _ _ = Nothing



step :: Id -> StorageTyping -> Constructor -> [Behaviour] -> Inductive
step name store _ transs = Inductive stepType [] [stateVar, stateVar'] "Prop"
    [IConstr "stepC" [envVar, stateVar, nextAddrVar, stateVar', nextAddrVar'] []
    [ extStepType <+> terms [envVar, stateVar, nextAddrVar, stateVar', nextAddrVar']
    , stepType <+> terms [stateVar, stateVar']]]
      ([multistep, unknownCall, extStep name store, localStep name transs] ++ (transition' store <$> transs))

stepBefore :: T.Text
stepBefore =
  definition stepBeforeType (declTerms [boundVar, stateVar, stateVar']) $
    "exists" <+> declTerms [envVar, nextAddrVar, nextAddrVar'] <> "," <+> extStepType <+> terms [envVar, stateVar, nextAddrVar, stateVar', nextAddrVar']
    <+> "/\\" <+> term nextAddrVar' <+> "<=" <+> term boundVar


combine :: [a] -> [(a,a)]
combine lst = combine' lst []
  where
    combine' [] acc = concat acc
    combine' (x:xs) acc =
      let xcomb = [ (x, y) | y <- xs] in
      combine' xs (xcomb:acc)

-- | Predicate that holds if p is an address of known contract type
-- in the given state
contractAddressIn :: Id -> StorageTyping -> T.Text
contractAddressIn name store = printInductive $ Inductive
  contractAddressInType
  []
  [stateVar, pVar]
  "Prop"
  ( IConstr "addressOf_This" [stateVar] []
            [ contractAddressInType <+> term stateVar <+> parens (addrField <+> term stateVar) ]
    : mapMaybe (uncurry subCAddr) (M.toList localStore) )
  []
  where
    localStore = contractStore name store
    pVar = Term "p" addressType

    subCAddr :: Id -> (ValueType, Integer) -> Maybe InductiveConstr
    subCAddr var (ValueType (TContract cid), _) = Just $ IConstr ("addressOf_" <> varp)
      [stateVar, pVar]
      []
      [ T.pack cid <.> contractAddressInType <+> parens (varp <+> term stateVar) <+> term pVar
      , contractAddressInType <+> terms [stateVar, pVar]
      ]
      where varp = T.pack var
    subCAddr _ _ = Nothing

slotContractName :: ValueType -> Maybe Id
slotContractName (ValueType (TContract cid)) = Just cid
slotContractName _ = Nothing

noAliasing :: Id -> StorageTyping -> T.Text
noAliasing name store = printInductive $ Inductive
  noAliasingType
  []
  [stateVar]
  "Prop"
  [IConstr "noAliasingC" [stateVar] [] bodyItems]
  []
  where
    bodyItems =
      (addressSubContractAliasing <$> storeContracts)
      <> (contractPairAliasing <$> contractPairs)
      <> (subContractAliasing <$> storeContracts)
      <> [noAliasingType <+> term stateVar]

    localStore = contractStore name store
    storeContracts = M.toList $ M.mapMaybe (slotContractName . fst) localStore
    contractPairs = filter (not. uncurry (==)) $ combine storeContracts

    addressSubContractAliasing :: (Id, Id) -> T.Text
    addressSubContractAliasing (cvar, cid) =
      parens $ forAll (parens ("p : address")) <+>
        ( T.pack cid <.> contractAddressInType <+> parens (T.pack cvar <+> term stateVar) <+> "p") <+> "->"
        <+> (parens (addrField <+> term stateVar) <+> "<>" <+> "p")

    contractPairAliasing :: ((Id, Id), (Id, Id)) -> T.Text
    contractPairAliasing ((cvar1, cid1), (cvar2, cid2)) =
      parens $ forAll (parens ("p p' : address")) <+>
        ( T.pack cid1 <.> contractAddressInType <+> parens (T.pack cvar1 <+> term stateVar) <+> "p") <+> "->"
        <+> ( T.pack cid2 <.> contractAddressInType <+> parens (T.pack cvar2 <+> term stateVar) <+> "p'") <+> "->"
        <+> ("p" <+> "<>" <+> "p'")

    subContractAliasing :: (Id, Id) -> T.Text
    subContractAliasing (cvar, cid) = T.pack cid <.> noAliasingType <+> parens (T.pack cvar <+> term stateVar)


coqbound :: T.Text -> ValueType -> Maybe T.Text
coqbound v (ValueType (TContract cid)) = pure $
  "0 <=" <+> T.pack cid <.> addrField <+> parens v <+> "<= UINT_MAX 160"
  --, T.pack cid <.> integerBoundsType <+> parens v ]
coqbound v (ValueType TAddress) = pure $
  "0 <=" <+> v <+> "<= UINT_MAX 160"
coqbound v (ValueType (TInteger n Unsigned)) = pure $
  "0 <=" <+> v <+> "<= UINT_MAX" <+> T.pack (show n)
coqbound v (ValueType (TInteger n Signed)) = pure $
  "INT_MIN" <+> T.pack (show n) <+> "<=" <+> v <+> "<= INT_MAX" <+> T.pack (show n)
coqbound v (ValueType t@(TMapping _ _)) = case unfoldMappingType t of
  (length -> i, ValueType TAddress) -> pure $ parens $
    "forall" <+> ixs i <> ", 0 <=" <+> v <+> ixs i <+> "<= UINT_MAX 160"
  (length -> i, ValueType (TInteger n Unsigned)) -> pure $ parens $
    "forall" <+> ixs i <> ", 0 <=" <+> v <+> ixs i <+> "<= UINT_MAX" <+> T.pack (show n)
  (length -> i, ValueType (TInteger n Signed)) -> pure $ parens $
    "forall" <+> ixs i <> ", INT_MIN" <+> T.pack (show n) <+> "<=" <+> v <+> ixs i <+> "<= INT_MAX" <+> T.pack (show n)
  _ -> Nothing
  where
    ixs n = T.unwords $ T.pack . (<>) "i" . show <$> [0..(n-1)]
coqbound _ _ = Nothing

intBoundsRec :: Id -> StorageTyping -> T.Text
intBoundsRec name store = printInductive $ Inductive
  integerBoundsType
  []
  [stateVar]
  "Prop"
  [IConstr "integerBoundsC" [stateVar] [] bodyItems]
  []
  where
    bodyItems = maybeToList (coqbound (T.pack name <.> addrField <+> term stateVar) (ValueType TAddress))
                <> (M.elems $ M.mapMaybeWithKey go localStore)
                <> [integerBoundsType <+> term stateVar]

    localStore = contractStore name store

    go :: Id -> (ValueType, Integer) -> Maybe T.Text
    go v (t,_) = coqbound (T.pack v <+> term stateVar) t

interfaceConstraints :: Interface -> [(T.Text, T.Text)]
interfaceConstraints (Interface _ decls) = argsConstraints decls

argsConstraints :: [Arg] -> [(T.Text, T.Text)]
argsConstraints args = concatMap go args <> argConsistency args
  where go (Arg (ContractArg _ cid) (T.pack -> v)) =
          [ ("argConstraints_nextAddr_" <> v, T.pack cid <.> nextAddrConstraintType <+> term nextAddrVar <+> v)
          , ("argConstraints_reachBefore_" <> v, T.pack cid <.> reachableBeforeType <+> term nextAddrVar <+> v)
          , ("argConstraints_intBounds_" <> v, T.pack cid <.> integerBoundsType <+> v) ]
          -- <> coqbound (T.pack v) (argToValueType t)
        go (Arg t@(AbiArg _) v) =
          maybeToList $ fmap ("argConstraints_intBounds_" <> T.pack v,) $ coqbound (T.pack v) (argToValueType t)

-- NOTE: do we also need to compare within the given states? see hevm/pass/cast-4
interfaceConsistency :: Interface -> [(T.Text, T.Text)]
interfaceConsistency (Interface _ decls) = argConsistency decls

-- NOTE: do we also need to compare within the given states? see hevm/pass/cast-4
argConsistency :: [Arg] -> [(T.Text, T.Text)]
argConsistency args = concatMap (uncurry consistency) contractArgPairs
  where
    contractArgs = mapMaybe contractArg args
    contractArgPairs = combine contractArgs

    contractArg (Arg (ContractArg _ c) v) = Just (c,v)
    contractArg _ = Nothing

    consistency :: (Id, Id) -> (Id, Id) -> [(T.Text, T.Text)]
    consistency (c1, (T.pack -> a1)) (c2, (T.pack -> a2)) | c1 == c2 =
      [ ("consistency_" <> a1 <> "_eq_" <> a2 , T.pack c1 <.> addrField <+> a1 <+> "=" <+> T.pack c2 <.> addrField <+> a2
        <+> "->" <+> a1 <+> "=" <+> a2)
      , ("consistency_" <> a1 <> "_neq_" <> a2, T.pack c1 <.> addrField <+> a1 <+> "<>" <+> T.pack c2 <.> addrField <+> a2
        <+> "->" <+> "forall" <+> parens ("p p' : " <> addressType) <> ","
        <+> T.pack c1 <.> addressInType <+> a1 <+> "p" <+> "->" <+> T.pack c2 <.> addressInType <+> a2 <+> "p'"  <+> "->" <+> "p <> p'")]
    consistency (c1, (T.pack -> a1)) (c2, (T.pack -> a2)) =
      [ ("consistency_" <> a1 <> "_neq_" <> a2, "forall" <+> parens ("p p' : " <> addressType) <> ","
        <+> T.pack c1 <.> addressInType <+> a1 <+> "p" <+> "->" <+> T.pack c2 <.> addressInType <+> a2 <+> "p'"  <+> "->" <+> "p <> p'")]


-- | definition of reachable states
reachable :: T.Text
reachable = definition
  reachableType (declTerm stateVar) value
  where
    value = "exists" <+> declTerm stateVar' <> "," <+> initStateType <+> term stateVar'
      <+> "/\\" <+> multistepType <+> term stateVar' <+> term stateVar

reachableBefore :: T.Text
reachableBefore = definition
  reachableBeforeType (declTerms [boundVar, stateVar]) value
  where
    value = "exists" <+> declTerm stateVar' <> "," <+> initStateBeforeType <+> term boundVar <+> term stateVar'
      <+> "/\\" <+> multistepBeforeType <+> term boundVar <+> term stateVar' <+> term stateVar

-- | specialization of generic multistep
--multistep :: T.Text
--multistep = definition
--  multistepType (parens $ term stateVar <+> term stateVar' <+> ":" <+> stateType) value
--  where
--    value = multistepType <+> stepType <+> term stateVar <+> term stateVar'
{-
multistep :: Inductive
multistep = Inductive multistepType [] [stateVar, stateVar'] "Prop"
    [ IConstr "multiRefl" [stateVar] [] [multistepType <+> terms [stateVar, stateVar]]
    , IConstr "multiTrans" [stateVar, iSTATE, stateVar'] []
      [ multistepType <+> terms [stateVar, iSTATE]
      , stepType <+> terms [iSTATE, stateVar']
      , multistepType <+> terms [stateVar, stateVar']] ]
    []
  where iSTATE = (Term "iSTATE" stateType)
  -}

multistep :: Inductive
multistep = Inductive multistepType [] [stateVar, stateVar'] "Prop"
    [ IConstr "multiRefl" [stateVar] [] [multistepType <+> terms [stateVar, stateVar]]
    , IConstr "multiTrans" [stateVar, iSTATE, stateVar'] []
      [ multistepType <+> terms [stateVar, iSTATE]
      , stepType <+> terms [iSTATE, stateVar']
      , multistepType <+> terms [stateVar, stateVar']] ]
    []
  where iSTATE = (Term "iSTATE" stateType)

unknownCall :: Inductive
unknownCall = Inductive unknownCallType [] [valVar, stateVar, stateVar', successVar] "Prop" 
    [ IConstr "unknownSuccess" [valVar, stateVar, stateVar'] []
      [ multistepType <+> parens (sendValueStateType <+> terms [stateVar, valVar]) <+> terms [stateVar']
      , unknownCallType <+> terms [valVar, stateVar, stateVar'] <+> "true"]
    , IConstr "unknownRevert" [valVar, stateVar, stateVar'] [] [unknownCallType <+> terms [valVar, stateVar, stateVar] <+> "false"]]
    []
  where
    successVar = Term "success" "bool"
    valVar = Term "v" "Z"

unknownCallType :: T.Text
unknownCallType = "unknownCall"

multistepBefore :: T.Text
multistepBefore = definition
  multistepBeforeType (declTerms [boundVar, stateVar, stateVar']) value
  where
    value = "ActLib" <.> multistepType <+> parens (stepBeforeType <+> term boundVar) <+> term stateVar <+> term stateVar'

-- | definition of reachable states from initial constructor parameters
reachableFromInit :: Constructor -> T.Text
reachableFromInit (Constructor _ _ i _ _ _ _ ) = definition
  reachableFromInitType (declTerms ([envVar] ++ ifaceTerms i ++ [nextAddrVar, stateVar])) value
  where
    value = "exists" <+> declTerms [stateVar', nextAddrVar'] <> "," <+> constructorType <+> terms ([envVar] ++ ifaceTerms i ++ [nextAddrVar, stateVar', nextAddrVar'])
      <+> "/\\" <+> multistepType <+> term stateVar' <+> term stateVar





{-
-- | definition of a base state
base :: StorageTyping -> Id -> Id -> Interface -> [StorageUpdate] -> T.Text
base store name createsName i updates =
  let (s, bindings, finalI) = stateval True store name (\_ t -> defaultVal t) updates in
  definition (T.pack createsName) (nextAddrDecl <+> envDecl <+> interface i)
    (foldr (\(_,b) s' -> "let" <+> b <+> "in\n" <> s') (tuple (iNextAddr finalI) s) bindings)

transition :: StorageTyping -> Id -> Id -> Interface -> [StorageUpdate] -> T.Text
transition store name cname i rewrites =
  let (s, bindings, finalI) = stateval False store cname (\r _ -> ref r) rewrites in
  definition (T.pack name) (nextAddrDecl <+> envDecl <+> stateDecl <+> interface i)
    (foldr (\(_,b) s' -> "let" <+> b <+> "in\n" <> s') (tuple (iNextAddr finalI) s) bindings)
    -}


{-
-- | inductive definition of a return claim
-- ignores claims that do not specify a return value
retVal :: Id -> Interface -> [Case] -> T.Text
retVal _ _ [] = ""
retVal _ _ ((Case _ _ (_,Nothing)):_) = ""
retVal name i cases@((Case _ _ (_, Just ret0)):_) = do
  inductive
    (T.pack name <> returnSuffix)
    (envDecl <+> interface i <+> stateDecl <+> nextAddrDecl )
    (returnType ret0 <> " -> Prop")
    caseCtors
  where
    retname n = n <> returnSuffix

    caseCtors = (evalSeq caseCtor cases)

    caseCtor :: Case -> Fresh (T.Text, T.Text, T.Text)
    caseCtor (Case _ _ (_, Nothing)) = error "Internal error: Case does not return"
    caseCtor (Case _ caseCond (_, Just ret)) = do
      -- name' <- fresh name
      caseId <- getIncr
      pure (T.pack name <> caseSuffix caseId <> returnSuffix, "", caseBody)
      where 
        caseBody = (indent 2) . implication . concat $
          [ [(T.pack name) <> "_conds" <+> envVar <+> arguments i <+> stateVar <+> nextAddrVar ]
          , [ coqprop caseCond ]
          , [retname (T.pack name) <+> envVar <+> arguments i <+> stateVar <+> nextAddrVar <+> typedexp ret]
          ]

-- | Definition of postcondition claim for constructor
postCondConstr :: Constructor -> [T.Text]
postCondConstr (Constructor _ cname iface _ _ postcs _) = evalSeq (go cname iface) postcs
  where
  go :: Id -> Interface -> Exp ABoolean -> Fresh T.Text
  go name i postc = do
    postName <- fresh (name <> "_post")
    pure $ definition postName "" body
    where
      body = indent 2 $ T.unlines
        [ forAll $ nextAddrDecl <+> envDecl <+> stateDecl' <+> interface i
        , implication . concat $
          [ [initPrecsType <+> nextAddrVar <+> envVar <+> arguments i]
          , [stateVar' <+> "=" <+> "snd" <+> parens (T.pack name <+> nextAddrVar <+> envVar <+> arguments i)]
          , [coqprop postc]
          ]
        ]

-- | Definition of postcondition claim for behaviour cases
-- TODO: need way to call behaviour with all cases, maybe through transition predicate?
postCondBehv :: Behaviour -> [T.Text]
postCondBehv (Behaviour _ bname _ iface _ _ postcs) = evalSeq (go bname iface) postcs
  where
  go :: Id -> Interface -> Exp ABoolean -> Fresh T.Text
  go name i postc = do
    postName <- fresh (name <> "_post")
    pure $ definition postName "" body
    where
      body = indent 2 $ T.unlines
        [ forAll $ nextAddrDecl <+> nextAddrDecl' <+> envDecl <+> stateDecl <+> stateDecl' <+> interface i
        , implication . concat $
          [ [T.pack bname <> "_conds" <+> envVar <+> arguments i <+> stateVar <+> nextAddrVar ]
          , [reachableType <+> stateVar]
          , [(T.pack bname <> "_transition" <+> envVar <+> arguments i <+> stateVar <+> nextAddrVar <+> stateVar'<+> nextAddrVar' )]
          , [coqprop postc]
          ]
        ]
        -}

-- | Definition of invariant proposition
invariants :: Interface -> [Invariant] -> T.Text
invariants _ [] = ""
invariants i invs =
  definition "invariants" (declTerms ([nextAddrVar, envVar, stateVar] ++ ifaceTerms i)) $ indent 2 . conjuction $ invariantProp <$> invs
  where
    invariantProp :: Invariant -> T.Text
    invariantProp (Invariant _ _ _ (PredTimed p _)) = coqprop p


-- | Definition of invariant claim at constructor poststate
invariantInit :: Constructor -> T.Text
invariantInit (Constructor _ _ i _ _ _ _) =
  definition invInitType (invPropDecl i) claim
  where
    claim = indent 2 $ T.unlines
      [ forAll $ declTerms ([envVar] ++ ifaceTerms i ++ [nextAddrVar, stateVar, nextAddrVar'])
      , implication . concat $
        [ [constructorType <+> terms ([envVar] ++ ifaceTerms i ++ [nextAddrVar, stateVar, nextAddrVar'])]
        , [invPropVar <+> terms ([envVar] ++ ifaceTerms i ++ [nextAddrVar, stateVar])]
        ]
      ]

-- | Definition of invariant claim for behaviour cases
invariantStep :: Constructor -> T.Text
invariantStep (Constructor _ _ i _ _ _ _) =
  definition invStepType (invPropDecl i) claim
  where
    claim = indent 2 $ T.unlines
      [ forAll $ declTerms ([envVar] ++ ifaceTerms i ++ [nextAddrVar, stateVar, stateVar'])
      , implication . concat $
        [ [initPrecsType <+> terms ([envVar] ++ ifaceTerms i ++ [nextAddrVar])]
        , [stepType <+> term stateVar <+> term stateVar']
        , [invPropVar <+> terms ([envVar] ++ ifaceTerms i ++ [nextAddrVar, stateVar])]
        , [invPropVar <+> terms ([envVar] ++ ifaceTerms i ++ [nextAddrVar, stateVar'])]
        ]
      ]

-- | Lemma extending invariant properties' hold to reachable states,
-- given proof of init and step invariance
invariantReachable :: Constructor -> T.Text
invariantReachable (Constructor _ _ i _ _ _ _) =
  lemma invReachType "" claim proof
  where
    claim = indent 2 $ T.unlines
      [ forAll (declTerms ([envVar] ++ ifaceTerms i ++ [nextAddrVar, stateVar]) <+> invPropDecl i
        <+> parens ("HIPinvInit :" <+> invInitType <+> invPropVar) <+> parens ("HIPinvStep :" <+> invStepType <+> invPropVar))
      , implication . concat $
        [ [reachableFromInitType <+> terms ([envVar] ++ ifaceTerms i ++ [nextAddrVar, stateVar])]
        , [invPropVar <+> terms ([envVar] ++ ifaceTerms i ++ [nextAddrVar, stateVar])]
        ]
      ]
    proof = T.unlines $
      [
        "Proof."
      , indent 2 . T.unlines $
        [ "intros" <+> terms ([envVar] ++ ifaceTerms i ++ [nextAddrVar, stateVar]) <+> invPropVar <+> "HIPinvInit HIPinvStep Hreach."
        , "unfold reachableFromInit in Hreach."
        , "destruct Hreach as [iState [iNA [Hinit Hmulti]]]."
        , "apply step_multi_step with (P := fun s s' =>" <+> invPropVar <+> terms ([envVar] ++ ifaceTerms i ++ [nextAddrVar]) <+> "s ->" <+> invPropVar <+> terms ([envVar] ++ ifaceTerms i ++ [nextAddrVar]) <+> "s' ) in Hmulti."
        , "- apply Hmulti."
        , "  eapply HIPinvInit; eassumption."
        , "- intros s s' Hstep."
        , "  destruct Hinit as [iNA' Hprecs]."
        , "  eapply HIPinvStep with (STATE := s) (STATE' := s'); eassumption."
        , "- unfold Relation_Definitions.reflexive."
        , "  intros."
        , "  assumption."
        , "- unfold Relation_Definitions.transitive."
        , "  intros s1 s2 s3 Ht1 Ht2 Ht3."
        , "  apply Ht2, Ht1."
        , "  assumption."
        ]
     , "Qed."
     ]

-- | Produce a state value from a list of storage updates
-- 'handler' defines what to do in cases where a given name isn't updated
-- TODO Lefteris: the order of `NextAddr`'s increments will follow the order in which the storage slots are stored in `StorageTyping`,
-- which is alphabetical since it is a mapping keyed on names. This is a divergance from the formalization, where increments follow the order
-- in which the the storage variables are defined. Not really important as addresses currently cannot be compared (right?), but fix at some point.
stateval :: Bool -> StorageTyping -> Id -> Int -> (Ref LHS -> ValueType -> T.Text) -> [StorageUpdate] -> T.Text
stateval newAddr store contract numInters handler updates =
  let text = (\(n, (t, _)) -> updateVar store updates handler (SVar nowhere Pre numInters contract n) t) <$> (M.toList store')
      -- (vals, bindings) = unzip texts
      --bindings' = concat bindings
      --finalBindings = if ctor then env1Binding : bindings' else bindings'
      --env1Binding = ([iNextAddr 1], "NextAddr1 = NextAddr + 1")
  in
  (T.unwords $ stateConstructor : addr : text)
  where
    addr = if newAddr then "NextAddr" else parens (T.pack contract <.> addrField <+> iState numInters)
    store' = contractStore contract store


contractStore :: Id -> StorageTyping -> Map Id (ValueType, Integer)
contractStore contract store = case M.lookup contract store of
  Just s -> s
  Nothing -> error $ "Internal error: cannot find constructor of " <> contract <> " in store"


-- | Check is an update update a specific storage reference
eqRef :: Ref LHS -> StorageUpdate -> Bool
eqRef r (Update _ r' _) = r == r'

-- | Check if an update updates a location that has a given storage
-- reference as a base
baseRef :: Ref LHS -> StorageUpdate -> Bool
baseRef baseref (Update _ r _) = hasBase r
  where
    hasBase (SVar _ _ _ _ _) = False -- TODO: check if resettag matters
    hasBase (RArrIdx _ r' _ _) = r' == baseref || hasBase r'
    --hasBase (RMapIdx _ r' _ _) = r' == baseref || hasBase r'
    hasBase (RField _ r' _ _) = r' == baseref || hasBase r'

iState :: Int -> T.Text
iState 0 = "STATE"
iState i = "STATE" <> T.pack (show i)
-- 
-- iState' :: Int -> T.Text
-- iState' i = "STATE" <> T.pack (show i) <> "'"

iNextAddr :: Int -> T.Text
iNextAddr 0 = "NextAddr"
iNextAddr i = "NextAddr" <> T.pack (show i)

-- Returns the value of the state after all updates, as well as the relevant let-bindings for said state value
updateVar :: StorageTyping -> [StorageUpdate] -> (Ref LHS -> ValueType -> T.Text) -> Ref LHS -> ValueType -> T.Text
updateVar _ updates handler focus t@(ValueType (TMapping _ _)) =
  -- Note: If creates are allowed in indices then bindings should be collected from them.
  -- The result type cannot be a contract so no creates, and thus no bindings, are present there.
  foldl updatedVal (handler focus t) (filter (eqRef focus) updates)
    where
      updatedVal _ (Update TByteStr _ _) = error "bytestrings not supported"
      updatedVal _ (Update _ _ e) = mappingExp e 0

updateVar _ updates handler focus t@(ValueType _) = foldl updatedVal (handler focus t) (filter (eqRef focus) updates)
    where
      updatedVal _ (Update TByteStr _ _) = error "bytestrings not supported"
      updatedVal _ (Update _ _ e) = coqexp e



-- | produce a block of declarations from an interface
ifaceTerms :: Interface -> [Term]
ifaceTerms (Interface _ decls) = argTerms decls

argTerms :: [Arg] -> [Term]
argTerms args = argT <$> args
  where argT (Arg (AbiArg AbiAddressType) name) = Term (T.pack name) (abiType AbiAddressType)
        argT (Arg (ContractArg _ cid) name) = Term (T.pack name) (T.pack cid <.> "State")
        argT (Arg (AbiArg t) name) = Term (T.pack name) (abiType t)

-- | produce a block of declarations from an interface
interface' :: Interface -> [T.Text]
interface' (Interface _ decls) =
  map decl decls where
  decl (Arg (AbiArg AbiAddressType) name) = parens $ T.pack name <+> ":" <+> abiType AbiAddressType
  decl (Arg (ContractArg _ cid) name) = parens $ T.pack name <+> ":" <+> T.pack cid <.> "State"
  decl (Arg (AbiArg t) name) = parens $ T.pack name <+> ":" <+> abiType t

interfaceType :: Interface -> T.Text
interfaceType (Interface _ []) = ""
interfaceType (Interface _ decls) = (T.pack "->") <+> (
  T.intercalate " -> " $ map decl decls)
  where
  decl (Arg (AbiArg AbiAddressType) _) = abiType AbiAddressType
  decl (Arg (ContractArg _ cid) _) = T.pack cid <.> "State"
  decl (Arg (AbiArg t) _) = abiType t

arguments :: Interface -> T.Text
arguments (Interface _ decls) = argumentsA decls

argumentsA :: [Arg] -> T.Text
argumentsA args = T.unwords $ map (\(Arg _ name) -> T.pack name) args

-- | coq syntax for a value type
valueType :: ValueType -> T.Text
valueType (ValueType (TContract cid)) = T.pack cid <> "." <> "State" -- the type of a contract is its state record
valueType (ValueType (TMapping k t)) = valueType k <+> "->" <+> valueType t
valueType (ValueType t) = abiType $ toAbiType t

unfoldMappingType :: TValueType AMapping -> ([ValueType], ValueType)
unfoldMappingType mt = go (ValueType mt) []
  where
    go :: ValueType -> [ValueType] -> ([ValueType], ValueType)
    go (ValueType (TMapping key t)) keys = go t (keys ++ [key])
    go t keys = (keys, t)

-- | coq syntax for an abi type
abiType :: AbiType -> T.Text
abiType (AbiUIntType _) = "Z"
abiType (AbiIntType _) = "Z"
abiType AbiAddressType = "address"
abiType AbiStringType = strMod <.> "string"
abiType AbiBoolType = "bool"
abiType a = error $ show a

-- | coq syntax for a return type
returnType :: TypedExp -> T.Text
returnType (TExp (TInteger _ _) _) = "Z"
returnType (TExp TUnboundedInt _) = "Z"
returnType (TExp TAddress _) = "Z"
returnType (TExp TBoolean _) = "bool"
returnType (TExp (TContract _) _) = error "contracts not allowed as return types"
returnType (TExp (TMapping _ _) _) = error "mappings not supported as return types"
returnType (TExp TByteStr _) = error "bytestrings not supported"
returnType (TExp (TStruct _) _) = error "structs not supported"
returnType (TExp (TArray _ _) _) = error "arrays not supported"


-- | default value for a given type
-- this is used in cases where a value is not set in the constructor
defaultVal :: ValueType -> T.Text
defaultVal (ValueType (TMapping _ t)) = parens $
  "fun" <+> "_" <+> "=>" <+> defaultVal t
defaultVal (ValueType (TContract cid)) = T.pack cid <.> "zeroState"
defaultVal (ValueType t) = abiVal $ toAbiType t

abiVal :: AbiType -> T.Text
abiVal (AbiUIntType _) = "0"
abiVal (AbiIntType _) = "0"
abiVal AbiAddressType = "0"
abiVal AbiStringType = strMod <.> "EmptyString"
abiVal AbiBoolType = "false"
abiVal _ = error "TODO: missing default values"

-- | coq syntax for an expression
coqexp :: Exp a -> T.Text
-- booleans
coqexp (LitBool _ True)  = "true"
coqexp (LitBool _ False) = "false"
coqexp (And _ e1 e2)  = parens $ "andb"    <+> coqexp e1 <+> coqexp e2
coqexp (Or _ e1 e2)   = parens $ "orb"     <+> coqexp e1 <+> coqexp e2
coqexp (Impl _ e1 e2) = parens $ "implb"   <+> coqexp e1 <+> coqexp e2
coqexp (Eq _ _ e1 e2)   = parens $ coqexp e1  <+> "=?" <+> coqexp e2
coqexp (NEq _ _ e1 e2)  = parens $ "negb" <+> parens (coqexp e1  <+> "=?" <+> coqexp e2)
coqexp (Neg _ e)      = parens $ "negb" <+> coqexp e
coqexp (LT _ e1 e2)   = parens $ coqexp e1 <+> "<?"  <+> coqexp e2
coqexp (LEQ _ e1 e2)  = parens $ coqexp e1 <+> "<=?" <+> coqexp e2
coqexp (GT _ e1 e2)   = parens $ coqexp e2 <+> "<?"  <+> coqexp e1
coqexp (GEQ _ e1 e2)  = parens $ coqexp e2 <+> "<=?" <+> coqexp e1

-- integers
coqexp (LitInt _ i) = T.pack $ show i
coqexp (Add _ e1 e2) = parens $ coqexp e1 <+> "+" <+> coqexp e2
coqexp (Sub _ e1 e2) = parens $ coqexp e1 <+> "-" <+> coqexp e2
coqexp (Mul _ e1 e2) = parens $ coqexp e1 <+> "*" <+> coqexp e2
coqexp (Div _ e1 e2) = parens $ coqexp e1 <+> "/" <+> coqexp e2
coqexp (Mod _ e1 e2) = parens $ "Z.modulo" <+> coqexp e1 <+> coqexp e2
coqexp (Exp _ e1 e2) = parens $ coqexp e1 <+> "^" <+> coqexp e2
coqexp (IntMin _ n)  = parens $ "INT_MIN"  <+> T.pack (show n)
coqexp (IntMax _ n)  = parens $ "INT_MAX"  <+> T.pack (show n)
coqexp (UIntMin _ n) = parens $ "UINT_MIN" <+> T.pack (show n)
coqexp (UIntMax _ n) = parens $ "UINT_MAX" <+> T.pack (show n)

coqexp (InRange _ t e) = coqexp (And nowhere (LEQ nowhere (lowerBound t) e) $ LEQ nowhere e (upperBound t))

-- polymorphic
coqexp (VarRef _ _ r) = ref r
coqexp (ITE _ b e1 e2) = parens $ "if"
                             <+> coqexp b
                             <+> "then"
                             <+> coqexp e1
                             <+> "else"
                             <+> coqexp e2

-- environment values
-- Relies on the assumption that Coq record fields have the same name
-- as the corresponding Haskell constructor
-- coqexp (IntEnv _ This) = parens $ addrField <+> stateVar
coqexp (IntEnv _ envVal) = parens $ T.pack (show envVal) <+> term envVar
coqexp (Address _ c e) = parens $ T.pack c <.> addrField <+> coqexp e

coqexp me@(Mapping _ _ _ _) = mappingExp me 0
coqexp me@(MappingUpd _ _ _ _ _) = mappingExp me 0

-- unsupported
coqexp Cat {} = error "bytestrings not supported"
coqexp Slice {} = error "bytestrings not supported"
coqexp ByStr {} = error "bytestrings not supported"
coqexp ByLit {} = error "bytestrings not supported"
coqexp ByEnv {} = error "bytestrings not supported"
coqexp Array {} = error "arrays not supported"

mappingExp :: Exp a -> Int -> T.Text
mappingExp (Mapping _ keyType valType@VType es) level = parens $
  "fun" <+> (anon <> (T.pack $ show level)) <+> "=>" <+>
  foldr (mappingElem level keyType) (defaultVal (ValueType valType)) es
mappingExp (MappingUpd _ r keyType _ es) level = parens $
  "fun" <+> (anon <> (T.pack $ show level)) <+> "=>" <+>
  foldr (mappingElem level keyType) (ref r <> (anon <> (T.pack $ show level))) es
mappingExp e _ = coqexp e

mappingElem :: Int -> TValueType a -> (Exp a, Exp b) -> T.Text -> T.Text
mappingElem level keyType (key, ve) elseText =
  "if" <+> boolScope (parens (anon <> T.pack (show level)) <+> eqsym keyType <+> coqexp key) <+>
  "then" <+> mappingExp ve (level + 1) <+>
  "else" <+> elseText

eqsym :: TValueType a -> T.Text
eqsym argType = case argType of
  TInteger _ _ -> "=?"
  TUnboundedInt -> "=?"
  TAddress -> "=?"
  TBoolean -> "=??"
  TMapping _ _ -> error "mapping as keys not supported"
  TByteStr -> error "bytestrings as keys not supported"
  TArray _ _ -> error "arrays as key not supported"
  TStruct _ -> error "structs as key not supported"
  TContract _ -> error "contracts as key not supported"


-- | coq syntax for a proposition
coqprop :: Exp ABoolean -> T.Text
coqprop (LitBool _ True)  = "True"
coqprop (LitBool _ False) = "False"
coqprop (And _ e1 e2)  = parens $ coqprop e1 <+> "/\\" <+> coqprop e2
coqprop (Or _ e1 e2)   = parens $ coqprop e1 <+> "\\/" <+> coqprop e2
coqprop (Impl _ e1 e2) = parens $ coqprop e1 <+> "->"  <+> coqprop e2
coqprop (Neg _ e)      = parens $ "not" <+> coqprop e
coqprop (Eq _ _ e1 e2)   = parens $ coqexp e1 <+> "="  <+> coqexp e2
coqprop (NEq _ _ e1 e2)  = parens $ coqexp e1 <+> "<>" <+> coqexp e2
coqprop (LT _ e1 e2)   = parens $ coqexp e1 <+> "<"  <+> coqexp e2
coqprop (LEQ _ e1 e2)  = parens $ coqexp e1 <+> "<=" <+> coqexp e2
coqprop (GT _ e1 e2)   = parens $ coqexp e1 <+> ">"  <+> coqexp e2
coqprop (GEQ _ e1 e2)  = parens $ coqexp e1 <+> ">=" <+> coqexp e2
coqprop (InRange _ t e) = coqprop (And nowhere (LEQ nowhere (lowerBound t) e) $ LEQ nowhere e (upperBound t))
coqprop (ITE _ b e1 e2) =
  parens $ "if" <+> coqbool b <+> "then" <+> coqexp e1 <+> "else" <+> coqexp e2
coqprop e@(VarRef _ TBoolean _) = parens $ coqexp e <+> "=" <+> "true"
-- coqprop e@(VarRef _ _ _) = error "ill formed proposition:" <+> T.pack (show e) --TODO: is this necessary?

coqbool :: Exp ABoolean -> T.Text
coqbool (LitBool _ True)  = "true"
coqbool (LitBool _ False) = "false"
coqbool (And _ e1 e2)  = parens $ "andb" <+> coqbool e1 <+> coqbool e2
coqbool (Or _ e1 e2)   = parens $ "orb" <+> coqbool e1 <+> coqbool e2
coqbool (Impl _ e1 e2) = parens $ "implb" <+> coqbool e1 <+> coqbool e2
coqbool (Neg _ e)      = parens $ "neqb" <+> coqbool e
coqbool (Eq _ t e1 e2)   = boolScope $ coqexp e1 <+> eqsym t <+> coqexp e2
coqbool (NEq _ t e1 e2)  = boolScope $ "negb" <+> parens (coqexp e1 <+> eqsym t <+> coqexp e2)
coqbool (LT _ e1 e2)   = parens $ coqexp e1 <+> "<?"  <+> coqexp e2
coqbool (LEQ _ e1 e2)  = parens $ coqexp e1 <+> "<=?" <+> coqexp e2
coqbool (GT _ e1 e2)   = parens $ coqexp e1 <+> ">?"  <+> coqexp e2
coqbool (GEQ _ e1 e2)  = parens $ coqexp e1 <+> ">=?" <+> coqexp e2
coqbool (InRange _ t e) = coqbool (And nowhere (LEQ nowhere (lowerBound t) e) $ LEQ nowhere e (upperBound t))
coqbool e@(VarRef _ TBoolean _) = parens $ coqexp e

coqbool e = error "ill formed proposition:" <+> T.pack (show e)

-- | coq syntax for a typed expression
typedexp :: TypedExp -> T.Text
typedexp (TExp _ e) = coqexp e

ref :: Ref k -> T.Text
ref (SVar _ Pre i cid name) = parens $ T.pack cid <.> T.pack name <+> term (iStateVar i)
ref (SVar _ Post i cid name) = parens $ T.pack cid <.> T.pack name <+> term (iStateVar' i)
ref (CVar _ _ name) = T.pack name
ref (RArrIdx _ r ix _) = parens $ ref r <+> coqexp ix
ref (RMapIdx _ (TRef _ _ r) ix) = parens $ ref r <+> typedexp ix
ref (RField _ r cid name) = parens $ T.pack cid <.> T.pack name <+> ref r

refState :: T.Text -> Ref k -> T.Text
refState s (SVar _ _ _ cid name) = parens $ T.pack cid <.> T.pack name <+> s
refState _ (CVar _ _ name) = T.pack name
refState s (RArrIdx _ r ix _) = parens $ refState s r <+> coqexp ix
refState s (RMapIdx _ (TRef _ _ r) ix) = parens $ refState s r <+> typedexp ix
refState s (RField _ r cid name) = parens $ T.pack cid <.> T.pack name <+> refState s r

-- | coq syntax for a list of arguments
coqargs :: [TypedExp] -> T.Text
coqargs es = T.unwords (map typedexp es)

fresh :: Id -> Fresh T.Text
fresh name = state $ \s -> (T.pack (name <> show s), s + 1)

freshId :: Id -> Fresh Id
freshId name = state $ \s -> (name <> show s, s + 1)

getIncr :: Fresh Int
getIncr = state $ \s -> (s, s + 1)

evalSeq :: Traversable t => (a -> Fresh b) -> t a -> t b
evalSeq f xs = evalState (sequence (f <$> xs)) 0

runSeq :: Traversable t => (a -> Fresh b) -> t a -> Int -> (t b, Int)
runSeq f xs iInit = runState (sequence (f <$> xs)) iInit

--- text manipulation ---

definition :: T.Text -> T.Text -> T.Text -> T.Text
definition name args value = T.unlines
  [ "Definition" <+> name <+> args <+> ":="
  , value <> "."
  ]

data Inductive = Inductive T.Text [Term] [Term] RocqType [InductiveConstr] [Inductive] -- last list: withs
data InductiveConstr = IConstr T.Text [Term] [Term] [T.Text] -- 1st [Term]: variable bindings
                                                         -- 2nd [Term]: named hypothesis   (same essentially, but print differently)

printInductive :: Inductive -> T.Text
printInductive i = inductive True i
  where
  inductive :: Bool -> Inductive -> T.Text
  inductive toplevel (Inductive name args indices ftype constructors withs) =
    let body =
          name <+> declTerms args <+> ":" <+> T.intercalate " -> " (snoc (rocqtype <$> indices) ftype) <+> ":=\n" <+>
          (indent 2 . T.unlines $ (<>) "| " . printInductiveConstructor <$> constructors)
    in case toplevel of
      True -> "Inductive" <+> body <> (T.unlines $ ("with" <+>) . inductive False <$> withs) <> "."

      False -> body <> (indent 2 . T.unlines $ ("with" <+>) . inductive False <$> withs)


printInductiveConstructor :: InductiveConstr -> T.Text
printInductiveConstructor (IConstr cname [] [] impls) =
  cname <+> ":\n" <> implication impls
printInductiveConstructor (IConstr cname [] namedhyps impls) =
  cname <+> ": forall\n" <> indent 2 (namedHyps namedhyps <> "," <> implication impls)
printInductiveConstructor (IConstr cname args namedhyps impls) =
  cname <+> ": forall" <+> declTerms args <+> "\n" <> indent 2 (namedHyps namedhyps <> "," <> implication impls)

-- inductive :: T.Text -> T.Text -> T.Text -> [(T.Text, T.Text, T.Text)] -> T.Text
-- inductive name args indices constructors = T.unlines
--   [ "Inductive" <+> name <+> args <+> ":" <+> indices <+> ":="
--   , T.unlines (((<>) "| " . uncurry3 inductiveConstructor) <$> constructors) <> "."
--   ]

inductiveConstructor :: T.Text -> T.Text -> T.Text -> T.Text
inductiveConstructor ctorName bindings body =
     ctorName <+> ":" <+> bindings <> "\n" <> body

lemma :: T.Text -> T.Text -> T.Text -> T.Text -> T.Text
lemma name args claim proof = T.unlines
  [ "Lemma" <+> name <+> args <+> ":"
  , claim <> "."
  , proof
  ]


-- | forall bindings
forAll :: T.Text -> T.Text
forAll "" = ""
forAll bindings = "forall" <+> bindings <> ","

-- | multiline implication
implication :: [T.Text] -> T.Text
implication xs = "   " <> T.intercalate "\n-> " xs

-- | multiline implication
namedHyps :: [Term] -> T.Text
namedHyps xs = T.unlines (declTerm <$> xs)
  --where go (n, h) = parens ( " H_" <> n <> " : " <> h <> " ")

-- | multiline conjuction
conjuction :: [T.Text] -> T.Text
conjuction [] = "   True"
conjuction xs = "   " <> T.intercalate "\n/\\ " xs

-- | wrap text in parentheses
parens :: T.Text -> T.Text
parens s = "(" <> s <> ")"

tuple :: T.Text -> T.Text -> T.Text
tuple a b = "(" <> a <> ", " <> b <> ")"

boolScope :: T.Text -> T.Text
boolScope s = "(" <> s <> ")%bool"

indent :: Int -> T.Text -> T.Text
indent n = T.unlines . fmap (T.replicate n " " <>) . T.lines

(<+>) :: T.Text -> T.Text -> T.Text
"" <+> t2 = t2
t1 <+> "" = t1
t1 <+> t2 = t1 <> " " <> t2

(<.>) :: T.Text -> T.Text -> T.Text
t1 <.> t2 = t1 <> "." <> t2

--- constants ---

type RocqType = T.Text  -- identifire and type
data Term = Term T.Text RocqType  -- identifire and type
  deriving (Show)

declTerm :: Term -> T.Text
declTerm (Term ident typ) = parens (ident <+> ":" <+> typ)

declTerms :: [Term] -> T.Text
declTerms ts = T.unwords (declTerm <$> ts)

term :: Term -> T.Text
term (Term ident _) = ident

terms :: [Term] -> T.Text
terms ts = T.unwords (term <$> ts)

rocqtype :: Term -> T.Text
rocqtype (Term _ rtype) = rtype

-- | string module name
strMod :: T.Text
strMod  = "Str"

-- | base state name
baseVar :: T.Text
baseVar = "BASE"

stateType :: T.Text
stateType = "State"

stateVar :: Term
stateVar = Term "STATE" stateType

stateVar' :: Term
stateVar' = Term "STATE'" stateType

iStateVar :: Int -> Term
iStateVar 0 = stateVar
iStateVar i = Term ("STATE" <> (T.pack $ show i)) stateType

iStateVar' :: Int -> Term
iStateVar' i = Term ("STATE" <> T.pack (show i) <> "'") stateType

nextVar :: Term
nextVar = Term "NEXT" addressType

iStateVars :: Int -> [Term]
iStateVars upto = iStateVar <$> [1..upto]

iStateVars' :: Int -> [Term]
iStateVars' upto = (concatMap (\i -> [iStateVar' (i-1), iStateVar i]) [1..upto])

iStateVarPairs' :: Int -> [(Term,Term)]
iStateVarPairs' upto = (fmap (\i -> (iStateVar' (i-1), iStateVar i)) [1..upto])

stateConstructor :: T.Text
stateConstructor = "state"

addressType :: T.Text
addressType = "address"

addrField :: T.Text
addrField = "addr"

addrFieldDecl :: T.Text
addrFieldDecl = addrField <> " : address"

returnSuffix :: T.Text
returnSuffix = "_ret"

postSuffix :: T.Text
postSuffix = "_post"

constructorType :: T.Text
constructorType = "constructor"

invInitType :: T.Text
invInitType  = "invariantInit"

invStepType :: T.Text
invStepType  = "invariantStep"

invReachType :: T.Text
invReachType  = "invariantReachable"

baseSuffix :: T.Text
baseSuffix = "_base"

stepSuffix :: T.Text
stepSuffix = "_step"

introSuffix :: T.Text
introSuffix = "_intro"

caseSuffix :: Int -> T.Text
caseSuffix i = "_case" <> T.pack (show i)

localStepType :: Id -> T.Text
localStepType name = T.pack name <> "_transition"

stepType :: T.Text
stepType = "step"

stepBeforeType :: T.Text
stepBeforeType = "stepBefore"

extStepType :: T.Text
extStepType = "transition"

addressInType :: T.Text
addressInType = "addressIn"

contractAddressInType :: T.Text
contractAddressInType = "addressIn"

noAliasingType :: T.Text
noAliasingType = "noAliasing"

nextAddrConstraintType :: T.Text
nextAddrConstraintType = "nextAddrConstraint"

initStateType :: T.Text
initStateType = "init"

initStateBeforeType :: T.Text
initStateBeforeType = "initBefore"

invPropVar :: T.Text
invPropVar = "IP"

invPropType :: Interface -> T.Text
invPropType (Interface _ decls) = T.intercalate " -> " $ concat [[envType], map decl' decls, [addressType, stateType, "Prop"]]
  where
  decl' (Arg (ContractArg _ cid) _) = T.pack cid <> ".State"
  decl' (Arg (AbiArg t) _) = abiType t

invPropDecl :: Interface -> T.Text
invPropDecl i = parens $ invPropVar <+> ":" <+> invPropType i

initPrecsType :: T.Text
initPrecsType = "constructor_conds"

behvPrecsType :: T.Text
behvPrecsType = "behvPrecs"

integerBoundsType :: T.Text
integerBoundsType = "stateIntegerBounds"

multistepType :: T.Text
multistepType = "multistep"

multistepBeforeType :: T.Text
multistepBeforeType = "multistepBefore"

reachableType :: T.Text
reachableType = "reachable"

reachableBeforeType :: T.Text
reachableBeforeType = "reachableBefore"

reachableFromInitType :: T.Text
reachableFromInitType = "reachableFromInit"

reachStep:: T.Text
reachStep= "reach_step"

nextAddrType :: T.Text
nextAddrType = "address"

nextAddrVar :: Term
nextAddrVar = Term "NextAddr" nextAddrType

nextAddrVar' :: Term
nextAddrVar' = Term "NextAddr'" nextAddrType

envType :: T.Text
envType = "Env"

envVar :: Term
envVar = Term "ENV" envType

envVar' :: Term
envVar' = Term "ENV'" envType

boundType :: T.Text
boundType = "address"

boundVar :: Term
boundVar = Term "BOUND" boundType

anon :: T.Text
anon = "_binding_"
