name: Deploy Book
on:
    workflow_dispatch:
jobs:
    build:
        name: Build Book
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v6
            
            - name: Install Nix
              uses: cachix/install-nix-action@v31
            
            - name: Use Cachix
              uses: cachix/cachix-action@v16
              with:
                  name: dapp
            
            - name: Build documentation
              id: build
              run: nix develop --ignore-environment --command make docs

            - name: Upload artifact
              id: deployment
              uses: actions/upload-pages-artifact@v4
              with:
                  path: doc/book
    deploy:
        name: Deploy Book to GitHub Pages
        needs: build
        permissions:
            pages: write
            id-token: write

        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        runs-on: ubuntu-latest
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4